language: cpp
compiler: clang
os:
  - linux
  - osx
env:
  global:
    - AUTOCONF=autoconf
    - PREFIX=$HOME/build/ptomato/mozjs/_install
    - PKG_CONFIG_PATH=$PREFIX/lib/pkgconfig
    - LDD=ldd

matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"

before_install:
  - eval "${MATRIX_EVAL}"
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install yasm; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then eval "LDD='otool -L'"; fi

before_script:
  - mkdir -p $PREFIX
  - mkdir -p _build
  - cd _build
script:
  - ../js/src/configure --prefix=$PREFIX --enable-posix-nspr-emulation --with-system-zlib --with-intl-api --disable-jemalloc && make -j3 && make install
  - cd ..
  - $PREFIX/bin/js59 -e 'print("OK");'
  - $CXX -o testjs -std=c++11 `pkg-config --cflags mozjs-59a1` testjs.cpp `pkg-config --libs mozjs-59a1` && LD_LIBRARY_PATH=$PREFIX/lib ./testjs
after_script:
  - ls -R $PREFIX
  - LD_LIBRARY_PATH=$PREFIX/lib $LDD $PREFIX/lib/libmozjs-59a1.so
  - LD_LIBRARY_PATH=$PREFIX/lib $LDD testjs
